export const REGISTER_NEW_USER_WITH_EMAIL_AND_PASSWORD = "PROFILE::REGISTER_NEW_USER_WITH_EMAIL_AND_PASSWORD";
export const USER_SIGN_IN = "PROFILE::USER_SIGN_IN";
export const USER_LOG_OUT = "PROFILE::USER_LOG_OUT";
